export default function useExerciseList() {
  const exerciseList = [
    { id: 1, type: '등', name: '풀업' },
    { id: 2, type: '등', name: '바벨 로우' },
    { id: 3, type: '등', name: '덤벨 로우' },
    { id: 4, type: '등', name: '펜들레이 로우' },
    { id: 5, type: '등', name: '시티드 로우 머신' },
    { id: 6, type: '등', name: '랫풀다운' },
    { id: 7, type: '등', name: '친업' },
    { id: 8, type: '등', name: '하이퍼 익스텐션' },
    { id: 9, type: '등', name: '굿모닝 엑서사이즈' },
    { id: 10, type: '등', name: '시티드 케이블 로우' },
    { id: 11, type: '등', name: '루마니안 데드리프트' },
    { id: 12, type: '등', name: '원암 덤벨 로우' },
    { id: 13, type: '등', name: '중량 풀업' },
    { id: 14, type: '등', name: '인클라인 바벨 로우' },
    { id: 15, type: '등', name: '인버티드 로우' },
    { id: 16, type: '등', name: '바벨 풀오버' },
    { id: 17, type: '등', name: '백 익스텐션' },
    { id: 18, type: '등', name: '중량 하이퍼 익스텐션' },
    { id: 19, type: '등', name: '중량 친업' },
    { id: 20, type: '등', name: '인클라인 덤벨 로우' },
    { id: 21, type: '등', name: '티바 로우 머신' },
    { id: 22, type: '등', name: '맥그립 랫풀다운' },
    { id: 23, type: '등', name: '스미스머신 로우' },
    { id: 24, type: '등', name: '케이블 암 풀다운' },
    { id: 25, type: '등', name: '정지 바벨 로우' },
    { id: 26, type: '등', name: '패러럴그립 랫풀다운' },
    { id: 27, type: '등', name: '리버스그립 랫풀다운' },
    { id: 28, type: '등', name: '플로어 시티드 케이블 로우' },
    { id: 29, type: '등', name: '어시스트 풀업 머신' },
    { id: 30, type: '등', name: '래터럴 와이드 풀다운' },
    { id: 31, type: '어깨', name: '레터널 레이즈 머신' },
    { id: 32, type: '어깨', name: '스미스머신 슬러그' },
    { id: 33, type: '어깨', name: '케이블 프론트 레이즈' },
    { id: 34, type: '어깨', name: '덤벨 프론트 레이즈' },
    { id: 35, type: '어깨', name: '시티드 덤벨 리어 레터럴 레이즈' },
    { id: 36, type: '어깨', name: '바벨 프론트 레이즈' },
    { id: 37, type: '어깨', name: '오버 헤드 프레스' },
    { id: 38, type: '어깨', name: '덤벨 숄더 프레스' },
    { id: 39, type: '어깨', name: '덤벨 레터널 레이즈' },
    { id: 40, type: '어깨', name: '비하인드 넥프레스' },
    { id: 41, type: '어깨', name: '페이스 풀' },
    { id: 42, type: '어깨', name: '업라이트 로우' },
    { id: 43, type: '어깨', name: '숄더 프레스 머신' },
    { id: 44, type: '어깨', name: '덤벨 슈러그' },
    { id: 45, type: '팔', name: '덤벨 해머컬' },
    { id: 46, type: '팔', name: '덤벨 킥백' },
    { id: 47, type: '팔', name: '덤벨 리스트 컬' },
    { id: 48, type: '팔', name: '이지바 컬' },
    { id: 49, type: '팔', name: '케이블 컬' },
    { id: 50, type: '팔', name: '바벨 프리쳐 컬' },
    { id: 51, type: '팔', name: '덤벨 프리쳐 컬' },
    { id: 52, type: '팔', name: '암 컬 머신' },
    { id: 53, type: '팔', name: '케이블 해머컬' },
    { id: 54, type: '팔', name: '케이블 익스텐션' },
    { id: 55, type: '팔', name: '케이블 삼두 익스텐션' },
    { id: 56, type: '팔', name: '클로즈 그립 푸쉬업' },
    { id: 57, type: '가슴', name: '체스트 프레스 머신' },
    { id: 58, type: '가슴', name: '펙덱 플라이 머신' },
    { id: 59, type: '가슴', name: '푸쉬업' },
    { id: 60, type: '가슴', name: '인클라인 덤벨 플라이' },
    { id: 61, type: '가슴', name: '덤벨 풀오버' },
    { id: 62, type: '가슴', name: '인클라인 벤치프레스 머신' },
    { id: 63, type: '가슴', name: '딥스' },
    { id: 64, type: '가슴', name: '스미스 벤치 프레스' },
    { id: 65, type: '가슴', name: '디클라인 덤벨 플라이' },
    { id: 66, type: '가슴', name: '디클라인 벤치프레스' },
    { id: 67, type: '가슴', name: '인클라인 푸쉬업' },
    { id: 68, type: '가슴', name: '시티드 딥스 머신' },
    { id: 69, type: '하체', name: '스쿼드' },
    { id: 70, type: '하체', name: '바벨 힙 쓰러스트' },
    { id: 71, type: '하체', name: '브이 스쿼트' },
    { id: 72, type: '하체', name: '힙 어브 덕션 머신' },
    { id: 73, type: '하체', name: '케이블 힙 어브덕션' },
    { id: 74, type: '하체', name: '핵 스쿼트 머신' },
    { id: 75, type: '하체', name: '스모 데드리프트' },
    { id: 76, type: '하체', name: '카프 레이즈' },
    { id: 77, type: '하체', name: '바벨 런지' },
    { id: 78, type: '하체', name: '레그 컬' },
    { id: 79, type: '하체', name: '레그 익스텐션 머신' },
    { id: 80, type: '하체', name: '점프 스쿼트' },
  ];

  return exerciseList;
}
